In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [6]:
# converting python list to numpy array
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [12]:
# multi dimensional array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_mat)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# common and quickly array generating
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# displaying points
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [44]:
np.linspace(5,800,1000)

array([  5.        ,   5.7957958 ,   6.59159159,   7.38738739,
         8.18318318,   8.97897898,   9.77477477,  10.57057057,
        11.36636637,  12.16216216,  12.95795796,  13.75375375,
        14.54954955,  15.34534535,  16.14114114,  16.93693694,
        17.73273273,  18.52852853,  19.32432432,  20.12012012,
        20.91591592,  21.71171171,  22.50750751,  23.3033033 ,
        24.0990991 ,  24.89489489,  25.69069069,  26.48648649,
        27.28228228,  28.07807808,  28.87387387,  29.66966967,
        30.46546547,  31.26126126,  32.05705706,  32.85285285,
        33.64864865,  34.44444444,  35.24024024,  36.03603604,
        36.83183183,  37.62762763,  38.42342342,  39.21921922,
        40.01501502,  40.81081081,  41.60660661,  42.4024024 ,
        43.1981982 ,  43.99399399,  44.78978979,  45.58558559,
        46.38138138,  47.17717718,  47.97297297,  48.76876877,
        49.56456456,  50.36036036,  51.15615616,  51.95195195,
        52.74774775,  53.54354354,  54.33933934,  55.13

In [49]:
# identified matrix
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [50]:
# random 
np.random.rand(5)

array([0.713862  , 0.31859374, 0.15806323, 0.16847508, 0.40716116])

In [52]:
np.random.randint(1,101,10)

array([74, 34, 72, 30, 93, 14, 35, 98, 91, 56])

In [59]:
arr = np.arange(1,31)

In [62]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [83]:
ranarr = np.random.randint(1,51,10)

In [81]:
ranarr

array([26, 33, 22, 22, 21, 11, 14, 46, 12, 50])

In [85]:
ranarr.max()

49

In [84]:
ranarr.min()

9

In [92]:
# getting the index position of maximum value in an array
ranarr.argmax()

8

In [89]:
# getting the index position of minium value in an array
ranarr.argmin()

7